/* The following code was generated by JFlex 1.3.5 on 23/04/20 15:35 */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 23/04/20 15:35 from the specification file
 * <tt>file:/D:/pl_grupo_T/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\31\1\0"+
    "\1\34\2\0\1\26\1\23\1\42\1\43\1\36\1\6\1\0\1\7"+
    "\1\12\1\37\1\11\11\10\1\44\1\35\1\32\1\40\1\33\2\0"+
    "\1\53\1\4\1\55\1\25\1\47\1\17\5\4\1\54\1\4\1\24"+
    "\1\52\2\4\1\51\1\22\1\50\1\16\5\4\4\0\1\5\1\0"+
    "\1\20\2\4\1\25\1\13\1\17\5\4\1\21\1\4\1\41\1\27"+
    "\2\4\1\15\1\22\1\14\1\16\5\4\1\45\1\30\1\46\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    46,    92,   138,    92,   184,   230,   230,   276,   322, 
      368,   414,   460,   506,   552,   598,    92,   644,    92,    92, 
      690,    92,   736,    92,    92,    92,    92,   598,    92,    92, 
       92,    92,    92,   782,   828,   874,   276,   368,   276,   322, 
      920,   966,  1012,  1058,  1104,  1150,   184,  1196,   736,  1242, 
     1288,  1334,  1380,  1426,  1472,   184,    92,   184,  1518,  1564, 
     1610,  1656,  1702,  1702,   184,  1748,  1794,   184,  1840,  1886, 
     1932,  1978,  2024,   184,  2070,  2116,  2162,   184
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\3\1\7\1\10\1\11"+
    "\1\12\1\13\1\6\1\14\2\6\1\15\1\16\2\6"+
    "\1\17\1\20\1\6\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\14\1\43\1\22"+
    "\1\16\1\6\1\44\56\3\60\0\1\5\57\0\2\6"+
    "\1\0\3\6\1\0\10\6\1\0\2\6\1\0\1\6"+
    "\11\0\1\6\5\0\7\6\10\0\1\45\1\12\1\46"+
    "\53\0\2\47\1\46\53\0\2\50\1\46\53\0\2\51"+
    "\50\0\2\6\1\0\3\6\1\0\2\6\1\52\5\6"+
    "\1\0\2\6\1\0\1\6\11\0\1\6\5\0\2\6"+
    "\1\52\4\6\4\0\2\6\1\0\3\6\1\0\5\6"+
    "\1\53\2\6\1\0\2\6\1\0\1\6\11\0\1\6"+
    "\5\0\4\6\1\53\2\6\4\0\2\6\1\0\3\6"+
    "\1\0\10\6\1\0\1\54\1\6\1\0\1\6\11\0"+
    "\1\54\5\0\7\6\56\55\4\0\2\6\1\0\3\6"+
    "\1\0\10\6\1\0\2\6\1\0\1\56\11\0\1\6"+
    "\5\0\3\6\1\56\3\6\4\0\2\6\1\0\3\6"+
    "\1\0\2\6\1\57\5\6\1\0\2\6\1\0\1\6"+
    "\11\0\1\6\5\0\2\6\1\57\4\6\31\0\1\60"+
    "\24\0\1\61\1\4\1\5\53\61\4\0\2\6\1\0"+
    "\3\6\1\0\10\6\1\0\1\62\1\6\1\0\1\6"+
    "\11\0\1\6\5\0\7\6\4\0\2\6\1\0\3\6"+
    "\1\0\10\6\1\0\2\6\1\0\1\6\11\0\1\6"+
    "\5\0\1\63\6\6\4\0\2\6\1\0\3\6\1\0"+
    "\10\6\1\0\2\6\1\0\1\6\11\0\1\6\5\0"+
    "\4\6\1\64\2\6\10\0\2\51\1\0\1\65\33\0"+
    "\1\65\12\0\2\6\1\0\3\6\1\0\3\6\1\66"+
    "\4\6\1\0\2\6\1\0\1\6\11\0\1\6\5\0"+
    "\7\6\4\0\2\6\1\0\3\6\1\0\6\6\1\67"+
    "\1\6\1\0\2\6\1\0\1\6\11\0\1\6\5\0"+
    "\5\6\1\67\1\6\4\0\2\6\1\0\3\6\1\0"+
    "\10\6\1\0\1\6\1\70\1\0\1\6\11\0\1\6"+
    "\5\0\7\6\23\0\1\71\36\0\2\6\1\0\3\6"+
    "\1\0\1\6\1\72\6\6\1\0\2\6\1\0\1\6"+
    "\11\0\1\6\5\0\1\6\1\72\5\6\7\0\1\73"+
    "\52\0\2\6\1\0\3\6\1\0\10\6\1\0\2\6"+
    "\1\0\1\6\11\0\1\6\5\0\1\6\1\74\5\6"+
    "\4\0\2\6\1\0\3\6\1\0\10\6\1\0\2\6"+
    "\1\0\1\6\11\0\1\6\5\0\4\6\1\75\2\6"+
    "\4\0\2\6\1\0\3\6\1\0\10\6\1\0\2\6"+
    "\1\0\1\6\11\0\1\6\5\0\2\6\1\76\4\6"+
    "\6\0\2\77\2\100\50\0\2\6\1\0\3\6\1\0"+
    "\1\101\7\6\1\0\2\6\1\0\1\6\11\0\1\6"+
    "\5\0\1\101\6\6\4\0\2\6\1\0\3\6\1\0"+
    "\7\6\1\66\1\0\2\6\1\0\1\6\11\0\1\6"+
    "\5\0\7\6\7\0\1\102\52\0\2\6\1\0\3\6"+
    "\1\0\10\6\1\0\2\6\1\0\1\6\11\0\1\6"+
    "\5\0\1\103\6\6\4\0\2\6\1\0\3\6\1\0"+
    "\10\6\1\0\2\6\1\0\1\6\11\0\1\6\5\0"+
    "\5\6\1\104\1\6\4\0\2\6\1\0\3\6\1\0"+
    "\10\6\1\0\2\6\1\0\1\6\11\0\1\6\5\0"+
    "\4\6\1\105\2\6\10\0\2\100\44\0\7\102\1\106"+
    "\46\102\4\0\2\6\1\0\3\6\1\0\10\6\1\0"+
    "\2\6\1\0\1\6\11\0\1\6\5\0\2\6\1\107"+
    "\4\6\4\0\2\6\1\0\3\6\1\0\10\6\1\0"+
    "\2\6\1\0\1\6\11\0\1\6\5\0\6\6\1\110"+
    "\7\102\1\111\46\102\4\0\2\6\1\0\3\6\1\0"+
    "\10\6\1\0\2\6\1\0\1\6\11\0\1\6\5\0"+
    "\3\6\1\112\3\6\4\0\2\6\1\0\3\6\1\0"+
    "\10\6\1\0\2\6\1\0\1\6\11\0\1\6\5\0"+
    "\1\6\1\113\5\6\7\102\1\114\23\102\1\5\22\102"+
    "\4\0\2\6\1\0\3\6\1\0\10\6\1\0\2\6"+
    "\1\0\1\6\11\0\1\6\5\0\1\115\6\6\7\102"+
    "\1\114\23\102\1\0\22\102\4\0\2\6\1\0\3\6"+
    "\1\0\10\6\1\0\2\6\1\0\1\6\11\0\1\6"+
    "\5\0\2\6\1\116\4\6";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     9,  1,  9,  9,  1,  9,  1,  9,  9,  9,  9,  1,  9,  9,  9,  9, 
     9,  1,  1,  1,  0,  0,  1,  0,  1,  1,  1,  1,  0,  1,  1,  0, 
     0,  1,  1,  1,  0,  1,  1,  1,  9,  1,  0,  1,  1,  1,  0,  1, 
     1,  0,  1,  1,  1,  0,  1,  1,  0,  1,  1,  0,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2208];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 140) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 6: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 79: break;
        case 23: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);  }
        case 80: break;
        case 77: 
          {  return symbolFactory.newSymbol("DCARACTER", DCARACTER); }
        case 81: break;
        case 18: 
        case 46: 
          {  return symbolFactory.newSymbol("OR", OR);  }
        case 82: break;
        case 5: 
        case 11: 
        case 12: 
        case 13: 
        case 15: 
        case 17: 
        case 33: 
        case 34: 
        case 35: 
        case 41: 
        case 42: 
        case 43: 
        case 45: 
        case 49: 
        case 50: 
        case 51: 
        case 53: 
        case 54: 
        case 59: 
        case 60: 
        case 61: 
        case 66: 
        case 68: 
        case 70: 
        case 71: 
        case 74: 
        case 76: 
          {  return symbolFactory.newSymbol("id", id); }
        case 83: break;
        case 40: 
        case 63: 
          {  return symbolFactory.newSymbol("REAL", REAL, Double.parseDouble(yytext())); }
        case 84: break;
        case 32: 
          {  return symbolFactory.newSymbol("RCORCH", RCORCH);  }
        case 85: break;
        case 31: 
          {  return symbolFactory.newSymbol("LCORCH", LCORCH);  }
        case 86: break;
        case 29: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 87: break;
        case 27: 
          {  return symbolFactory.newSymbol("UMINUS", UMINUS);  }
        case 88: break;
        case 28: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 89: break;
        case 9: 
        case 38: 
          {  return symbolFactory.newSymbol("INT", INT, Integer.parseInt(yytext()));  }
        case 90: break;
        case 64: 
          {  return symbolFactory.newSymbol("BOOLEAN", BOOLEAN, Boolean.parseBoolean(yytext())); }
        case 91: break;
        case 3: 
        case 4: 
          {                                }
        case 92: break;
        case 73: 
          {  return symbolFactory.newSymbol("DENTERO", DENTERO); }
        case 93: break;
        case 67: 
          {  return symbolFactory.newSymbol("DREAL", DREAL); }
        case 94: break;
        case 30: 
          {  return symbolFactory.newSymbol("DPTOS", DPTOS);  }
        case 95: break;
        case 7: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 96: break;
        case 20: 
          {  return symbolFactory.newSymbol("MENOR", MENOR);  }
        case 97: break;
        case 21: 
          {  return symbolFactory.newSymbol("MAYOR", MAYOR);  }
        case 98: break;
        case 24: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 99: break;
        case 26: 
          {  return symbolFactory.newSymbol("IGUAL", IGUAL);  }
        case 100: break;
        case 2: 
        case 8: 
        case 10: 
        case 14: 
        case 22: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 101: break;
        case 56: 
          {  return symbolFactory.newSymbol("CHAR", CHAR, yytext().charAt(1) ); }
        case 102: break;
        case 16: 
        case 55: 
          {  return symbolFactory.newSymbol("AND",AND);  }
        case 103: break;
        case 19: 
        case 57: 
          {  return symbolFactory.newSymbol("NOT", NOT);  }
        case 104: break;
        case 25: 
          {  return symbolFactory.newSymbol("DIV", DIV);  }
        case 105: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
