/* The following code was generated by JFlex 1.3.5 on 28/04/20 16:42 */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 28/04/20 16:42 from the specification file
 * <tt>file:/D:/pl_grupo_T/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\33\1\0"+
    "\1\36\2\0\1\30\1\25\1\43\1\44\1\40\1\6\1\50\1\7"+
    "\1\14\1\41\1\11\11\10\1\45\1\37\1\34\1\42\1\35\2\0"+
    "\1\22\1\13\1\51\1\27\1\15\1\21\2\4\1\52\2\4\1\23"+
    "\1\53\1\26\1\31\2\4\1\17\1\24\1\16\1\20\2\4\1\12"+
    "\2\4\4\0\1\5\1\0\1\22\1\13\1\51\1\27\1\15\1\21"+
    "\2\4\1\52\2\4\1\23\1\53\1\26\1\31\2\4\1\17\1\24"+
    "\1\16\1\20\2\4\1\12\2\4\1\46\1\32\1\47\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    44,    88,   132,    88,   176,   220,   220,   264,   308, 
      352,   396,   440,   484,   528,   572,   616,   660,   704,   748, 
       88,   792,    88,    88,   836,    88,   880,    88,    88,    88, 
       88,    88,    88,    88,    88,    88,    88,   924,   968,  1012, 
      396,  1056,  1100,  1144,  1188,  1232,  1276,  1320,  1364,  1408, 
     1452,  1496,  1540,  1584,  1628,  1672,  1716,   176,  1760,  1804, 
     1848,  1892,  1892,  1144,  1936,  1980,  2024,  2068,  2112,  2156, 
     2200,  2244,   176,  2288,  2332,    88,   176,  2376,  2420,  2464, 
     2508,  2552,  2596,   176,  2640,   176,  2684,  2728,  2772,  2816, 
      176,  2860,  2904,  2948,  2992,  3036,  3080,  3124,  3168,   176, 
     3212,  3256,  3300,  3344,  3388,  3432,   176,  3476,   176,  3520, 
     3564,   176,  3608,  3652,  3696,   176,  3740,   176,  3784,  2860, 
     3828,   176,   176,  3872,   176,  3916,  3960,   176
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\3\1\7\1\10\1\11"+
    "\1\12\1\6\1\13\1\14\1\15\1\16\1\17\1\6"+
    "\1\20\1\21\1\6\1\22\1\23\1\24\1\6\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\6\1\47\54\3\56\0\1\5\55\0\2\6"+
    "\1\0\5\6\1\0\10\6\1\0\2\6\1\0\1\6"+
    "\17\0\3\6\10\0\1\11\1\50\2\0\1\51\47\0"+
    "\2\11\2\0\1\51\1\52\46\0\2\53\1\54\1\0"+
    "\1\51\1\52\42\0\2\6\1\0\5\6\1\0\3\6"+
    "\1\55\4\6\1\0\2\6\1\0\1\6\17\0\3\6"+
    "\10\0\2\56\46\0\2\6\1\0\5\6\1\0\10\6"+
    "\1\0\1\57\1\6\1\0\1\6\17\0\3\6\4\0"+
    "\2\6\1\0\5\6\1\0\2\6\1\60\5\6\1\0"+
    "\2\6\1\0\1\6\17\0\3\6\4\0\2\6\1\0"+
    "\5\6\1\0\1\61\7\6\1\0\2\6\1\0\1\6"+
    "\17\0\3\6\4\0\2\6\1\0\5\6\1\0\3\6"+
    "\1\62\1\6\1\63\2\6\1\0\2\6\1\0\1\6"+
    "\17\0\1\6\1\64\1\6\4\0\2\6\1\0\5\6"+
    "\1\0\10\6\1\0\1\65\1\6\1\0\1\6\17\0"+
    "\3\6\4\0\2\6\1\0\5\6\1\0\1\6\1\66"+
    "\6\6\1\0\2\6\1\0\1\6\17\0\1\6\1\67"+
    "\1\6\54\70\4\0\2\6\1\0\5\6\1\0\10\6"+
    "\1\0\2\6\1\0\1\71\17\0\3\6\4\0\2\6"+
    "\1\0\5\6\1\0\2\6\1\72\5\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\33\0\1\73\20\0\1\33"+
    "\2\0\51\33\4\0\2\6\1\0\5\6\1\0\5\6"+
    "\1\74\2\6\1\0\2\6\1\0\1\6\17\0\3\6"+
    "\4\0\2\6\1\0\5\6\1\0\10\6\1\0\2\6"+
    "\1\0\1\6\17\0\1\6\1\75\1\6\10\0\2\53"+
    "\2\0\1\51\1\52\44\0\2\76\2\77\52\0\2\53"+
    "\2\0\1\51\47\0\2\100\1\0\1\100\1\0\1\100"+
    "\3\0\2\100\4\0\1\100\21\0\1\100\6\0\2\6"+
    "\1\0\5\6\1\0\6\6\1\101\1\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\10\0\2\56\3\0\1\52"+
    "\42\0\2\6\1\0\5\6\1\0\1\6\1\102\6\6"+
    "\1\0\2\6\1\0\1\6\17\0\3\6\4\0\2\6"+
    "\1\0\5\6\1\0\3\6\1\103\4\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\1\6\1\104\3\6\1\105\2\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\10\6\1\0\1\106\1\6\1\0\1\6\17\0"+
    "\3\6\4\0\2\6\1\0\5\6\1\0\6\6\1\107"+
    "\1\6\1\0\2\6\1\0\1\6\17\0\3\6\4\0"+
    "\2\6\1\0\5\6\1\0\10\6\1\0\1\110\1\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\10\6\1\0\1\6\1\111\1\0\1\6\17\0"+
    "\3\6\4\0\2\6\1\0\5\6\1\0\2\6\1\112"+
    "\5\6\1\0\2\6\1\0\1\6\17\0\3\6\4\0"+
    "\2\6\1\0\5\6\1\0\10\6\1\0\1\113\1\6"+
    "\1\0\1\6\17\0\3\6\25\0\1\114\32\0\2\6"+
    "\1\0\5\6\1\0\1\6\1\115\6\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\7\0\1\116\50\0\2\6"+
    "\1\0\5\6\1\0\2\6\1\117\5\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\1\120\7\6\1\0\2\6\1\0\1\6\17\0"+
    "\3\6\10\0\2\77\46\0\2\6\1\0\5\6\1\0"+
    "\1\121\7\6\1\0\2\6\1\0\1\6\17\0\3\6"+
    "\4\0\2\6\1\0\5\6\1\0\1\122\7\6\1\0"+
    "\2\6\1\0\1\123\17\0\3\6\4\0\2\6\1\0"+
    "\5\6\1\0\1\124\7\6\1\0\2\6\1\0\1\6"+
    "\17\0\3\6\4\0\2\6\1\0\5\6\1\0\3\6"+
    "\1\125\4\6\1\0\2\6\1\0\1\6\17\0\3\6"+
    "\4\0\2\6\1\0\5\6\1\0\6\6\1\126\1\6"+
    "\1\0\2\6\1\0\1\6\17\0\3\6\4\0\2\6"+
    "\1\0\5\6\1\0\10\6\1\0\2\6\1\0\1\6"+
    "\17\0\1\127\2\6\4\0\2\6\1\0\5\6\1\0"+
    "\7\6\1\103\1\0\2\6\1\0\1\6\17\0\3\6"+
    "\4\0\2\6\1\0\5\6\1\0\7\6\1\130\1\0"+
    "\2\6\1\0\1\6\17\0\2\6\1\131\4\0\2\6"+
    "\1\0\5\6\1\0\3\6\1\132\4\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\10\6\1\0\2\6\1\0\1\133\17\0\3\6"+
    "\7\0\1\134\50\0\2\6\1\0\5\6\1\0\5\6"+
    "\1\135\2\6\1\0\2\6\1\0\1\6\17\0\3\6"+
    "\4\0\2\6\1\0\5\6\1\0\10\6\1\0\1\136"+
    "\1\6\1\0\1\6\17\0\3\6\4\0\2\6\1\0"+
    "\5\6\1\0\5\6\1\137\2\6\1\0\2\6\1\0"+
    "\1\6\17\0\3\6\4\0\2\6\1\0\5\6\1\0"+
    "\2\6\1\140\5\6\1\0\2\6\1\0\1\6\17\0"+
    "\3\6\4\0\2\6\1\0\5\6\1\0\10\6\1\0"+
    "\1\141\1\6\1\0\1\6\17\0\3\6\4\0\2\6"+
    "\1\0\5\6\1\0\2\6\1\142\5\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\10\6\1\0\2\6\1\0\1\6\17\0\1\6"+
    "\1\143\1\6\4\0\2\6\1\0\5\6\1\0\10\6"+
    "\1\0\2\6\1\0\1\6\17\0\1\6\1\144\1\6"+
    "\4\0\2\6\1\0\5\6\1\0\10\6\1\0\2\6"+
    "\1\0\1\6\17\0\1\6\1\145\1\6\4\0\2\6"+
    "\1\0\5\6\1\0\10\6\1\0\2\6\1\0\1\6"+
    "\17\0\1\146\2\6\7\134\1\147\44\134\4\0\2\6"+
    "\1\0\5\6\1\0\10\6\1\0\2\6\1\0\1\6"+
    "\17\0\1\150\2\6\4\0\2\6\1\0\5\6\1\0"+
    "\1\6\1\151\6\6\1\0\2\6\1\0\1\6\17\0"+
    "\3\6\4\0\2\6\1\0\5\6\1\0\10\6\1\0"+
    "\1\152\1\6\1\0\1\6\17\0\3\6\4\0\2\6"+
    "\1\0\5\6\1\0\10\6\1\0\2\6\1\0\1\153"+
    "\17\0\3\6\4\0\2\6\1\0\5\6\1\0\10\6"+
    "\1\0\2\6\1\0\1\6\17\0\1\154\2\6\4\0"+
    "\2\6\1\0\5\6\1\0\10\6\1\0\1\155\1\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\10\6\1\0\2\6\1\0\1\156\17\0\3\6"+
    "\4\0\2\6\1\0\5\6\1\0\1\157\7\6\1\0"+
    "\2\6\1\0\1\6\17\0\3\6\4\0\2\6\1\0"+
    "\5\6\1\0\1\6\1\160\6\6\1\0\2\6\1\0"+
    "\1\6\17\0\3\6\7\134\1\161\44\134\4\0\2\6"+
    "\1\0\5\6\1\0\1\6\1\162\6\6\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\5\6\1\163\2\6\1\0\2\6\1\0\1\6"+
    "\17\0\3\6\4\0\2\6\1\0\5\6\1\0\10\6"+
    "\1\0\2\6\1\0\1\164\17\0\3\6\4\0\2\6"+
    "\1\0\5\6\1\0\1\165\7\6\1\0\2\6\1\0"+
    "\1\6\17\0\3\6\4\0\2\6\1\0\5\6\1\0"+
    "\10\6\1\0\1\166\1\6\1\0\1\6\17\0\3\6"+
    "\4\0\2\6\1\0\5\6\1\0\10\6\1\0\1\167"+
    "\1\6\1\0\1\6\17\0\3\6\7\134\1\161\25\134"+
    "\1\170\16\134\4\0\2\6\1\0\5\6\1\0\1\171"+
    "\7\6\1\0\2\6\1\0\1\6\17\0\3\6\4\0"+
    "\2\6\1\0\5\6\1\0\7\6\1\172\1\0\2\6"+
    "\1\0\1\6\17\0\3\6\4\0\2\6\1\0\5\6"+
    "\1\0\7\6\1\173\1\0\2\6\1\0\1\6\17\0"+
    "\3\6\4\0\2\6\1\0\5\6\1\0\1\6\1\174"+
    "\6\6\1\0\2\6\1\0\1\6\17\0\3\6\4\0"+
    "\2\6\1\0\5\6\1\0\2\6\1\175\5\6\1\0"+
    "\2\6\1\0\1\6\17\0\3\6\4\0\2\6\1\0"+
    "\5\6\1\0\2\6\1\176\5\6\1\0\2\6\1\0"+
    "\1\6\17\0\3\6\4\0\2\6\1\0\5\6\1\0"+
    "\5\6\1\177\2\6\1\0\2\6\1\0\1\6\17\0"+
    "\3\6\4\0\2\6\1\0\5\6\1\0\7\6\1\200"+
    "\1\0\2\6\1\0\1\6\17\0\3\6";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  9,  1,  9,  9,  1,  9,  1,  9,  9,  9,  9,  9, 
     9,  9,  9,  9,  9,  1,  1,  1,  0,  0,  0,  0,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  0,  1,  1,  0,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  0,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4004];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 22: 
        case 57: 
          {  return symbolFactory.newSymbol("OR", OR);  }
        case 129: break;
        case 5: 
        case 10: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 21: 
        case 37: 
        case 38: 
        case 44: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 56: 
        case 59: 
        case 60: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 70: 
        case 71: 
        case 73: 
        case 74: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 84: 
        case 86: 
        case 87: 
        case 88: 
        case 89: 
        case 92: 
        case 93: 
        case 94: 
        case 95: 
        case 96: 
        case 97: 
        case 98: 
        case 100: 
        case 101: 
        case 103: 
        case 104: 
        case 105: 
        case 107: 
        case 109: 
        case 110: 
        case 113: 
        case 114: 
        case 116: 
        case 118: 
        case 120: 
        case 123: 
        case 125: 
        case 126: 
          {  return symbolFactory.newSymbol("ID", ID); }
        case 130: break;
        case 54: 
          {  return symbolFactory.newSymbol("SI", SI ); }
        case 131: break;
        case 8: 
        case 9: 
        case 39: 
        case 62: 
          {  return symbolFactory.newSymbol("NUMBER", NUMBER, Double.parseDouble(yytext())); }
        case 132: break;
        case 45: 
          {  return symbolFactory.newSymbol("NUMBER", NUMBER, Double.parseDouble(yytext())); }
        case 133: break;
        case 26: 
        case 119: 
          {   }
        case 134: break;
        case 83: 
          {  return symbolFactory.newSymbol("BOOLEAN", BOOLEAN, Boolean.parseBoolean(yytext())); }
        case 135: break;
        case 117: 
          {  return symbolFactory.newSymbol("FUNCION", FUNCION); }
        case 136: break;
        case 106: 
          {  return symbolFactory.newSymbol("DENTERO", DENTERO); }
        case 137: break;
        case 28: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 138: break;
        case 25: 
          {  return symbolFactory.newSymbol("MAYOR", MAYOR);  }
        case 139: break;
        case 24: 
          {  return symbolFactory.newSymbol("MENOR", MENOR);  }
        case 140: break;
        case 7: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 141: break;
        case 11: 
          {  return symbolFactory.newSymbol("PUNTO", PUNTO); }
        case 142: break;
        case 30: 
          {  return symbolFactory.newSymbol("IGUAL", IGUAL);  }
        case 143: break;
        case 33: 
          {  return symbolFactory.newSymbol("DPTOS", DPTOS);  }
        case 144: break;
        case 85: 
          {  return symbolFactory.newSymbol("DREAL", DREAL); }
        case 145: break;
        case 99: 
          {  return symbolFactory.newSymbol("FINSI", FINSI ); }
        case 146: break;
        case 2: 
        case 18: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 147: break;
        case 63: 
          {  return symbolFactory.newSymbol("NUMBER", NUMBER, (double) Integer.parseInt(yytext().substring(2), 16));  }
        case 148: break;
        case 29: 
          {  return symbolFactory.newSymbol("DIV", DIV);  }
        case 149: break;
        case 23: 
        case 76: 
          {  return symbolFactory.newSymbol("NOT", NOT);  }
        case 150: break;
        case 20: 
        case 72: 
          {  return symbolFactory.newSymbol("AND",AND);  }
        case 151: break;
        case 122: 
          {  return symbolFactory.newSymbol("ENTONCES", ENTONCES ); }
        case 152: break;
        case 121: 
          {  return symbolFactory.newSymbol("MIENTRAS", MIENTRAS); }
        case 153: break;
        case 115: 
          {  return symbolFactory.newSymbol("DBOOLEAN", DBOOLEAN); }
        case 154: break;
        case 127: 
          {  return symbolFactory.newSymbol("FINMIENTRAS", FINMIENTRAS ); }
        case 155: break;
        case 27: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);  }
        case 156: break;
        case 6: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 157: break;
        case 36: 
          {  return symbolFactory.newSymbol("COMA", COMA);  }
        case 158: break;
        case 90: 
          {  return symbolFactory.newSymbol("SINO", SINO ); }
        case 159: break;
        case 124: 
          {  return symbolFactory.newSymbol("DCARACTER", DCARACTER); }
        case 160: break;
        case 19: 
          {  return symbolFactory.newSymbol("UMINUS", UMINUS);  }
        case 161: break;
        case 31: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 162: break;
        case 32: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 163: break;
        case 34: 
          {  return symbolFactory.newSymbol("LCORCH", LCORCH);  }
        case 164: break;
        case 35: 
          {  return symbolFactory.newSymbol("RCORCH", RCORCH);  }
        case 165: break;
        case 108: 
          {  return symbolFactory.newSymbol("RETURN", RETURN); }
        case 166: break;
        case 111: 
          {  return symbolFactory.newSymbol("STRUCT", STRUCT ); }
        case 167: break;
        case 75: 
          {  return symbolFactory.newSymbol("CHAR", CHAR, yytext().charAt(1) ); }
        case 168: break;
        case 3: 
        case 4: 
          {  }
        case 169: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
