
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int AND = 19;
  public static final int MENOR = 16;
  public static final int PLUS = 3;
  public static final int INT = 22;
  public static final int OR = 20;
  public static final int IGUAL = 18;
  public static final int RPAREN = 9;
  public static final int CHAR = 25;
  public static final int SEMI = 2;
  public static final int NOT = 21;
  public static final int LPAREN = 8;
  public static final int DPTOS = 10;
  public static final int BOOLEAN = 24;
  public static final int MAYOR = 17;
  public static final int EOF = 0;
  public static final int id = 26;
  public static final int DIV = 5;
  public static final int RCORCH = 14;
  public static final int DCARACTER = 13;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int DREAL = 12;
  public static final int REAL = 23;
  public static final int LCORCH = 15;
  public static final int DENTERO = 11;
  public static final int UMINUS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "DIV",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "DPTOS",
  "DENTERO",
  "DREAL",
  "DCARACTER",
  "RCORCH",
  "LCORCH",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "AND",
  "OR",
  "NOT",
  "INT",
  "REAL",
  "BOOLEAN",
  "CHAR",
  "id"
  };
}

